### ISSUE TITLE
try change `PULSE_INGEST_DRIVER`

### ISSUE THREAD

**Issue by salahhusa9** [laravel/pulse#138]
### Pulse Version

1.0@beta

### Laravel Version

10.10

### PHP Version

8.2.8

### Database Driver & Version

MySql 8 on linux azure cloud

### Description

change`PULSE_INGEST_DRIVER`, problem is you limit between `storage` and `redis`, me i want to use in: `azure_redis`

```php
    protected function registerIngest(): void
    {
        $this->app->bind(Ingest::class, fn (Application $app) => match ($app->make('config')->get('pulse.ingest.driver')) {
            'storage' => $app->make(StorageIngest::class),
            'redis' => $app->make(RedisIngest::class),
            default => throw new RuntimeException("Unknown ingest driver [{$app->make('config')->get('pulse.ingest.driver')}]."),
        });
    }
```

you can set defult as `RedisIngest`

### Steps To Reproduce

non

**Comment by timacdonald** [comment]
@salahhusa9 if Azure Redis works via `predis` or `phpredis` than it will already be supported.

If it does not you will need to build your own `Ingest` instance that supports it.

**Comment by salahhusa9** [comment]
```php
root@3e4a92a78ea6:/home/site/wwwroot# php artisan pulse:check
[2023-12-05 09:37:15] production.ERROR: Connection refused {"exception":"[object] (RedisException(code: 0): Connection refused at /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:161)
[stacktrace]
#0 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(161): Redis->connect('127.0.0.1', '6379', 0.0, NULL, 0, 0.0)
#1 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(90): Illuminate\\Redis\\Connectors\\PhpRedisConnector->establishConnection(Object(Redis), Array)
#2 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}(Object(Redis))
#3 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(81): tap(Object(Redis), Object(Closure))
#4 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(33): Illuminate\\Redis\\Connectors\\PhpRedisConnector->createClient(Array)
#5 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php(38): Illuminate\\Redis\\Connectors\\PhpRedisConnector->Illuminate\\Redis\\Connectors\\{closure}()
#6 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(110): Illuminate\\Redis\\Connectors\\PhpRedisConnector->connect(Array, Array)
#7 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Redis/RedisManager.php(91): Illuminate\\Redis\\RedisManager->resolve('default')
#8 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(340): Illuminate\\Redis\\RedisManager->connection('default')
#9 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(209): Illuminate\\Cache\\RedisStore->lockConnection()
#10 /home/site/wwwroot/vendor/laravel/pulse/src/Commands/CheckCommand.php(70): Illuminate\\Cache\\RedisStore->lock('laravel:pulse:c...', 5)
#11 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(36): Laravel\\Pulse\\Commands\\CheckCommand->handle(Object(Laravel\\Pulse\\Pulse), Object(Laravel\\Pulse\\Support\\CacheStoreResolver), Object(Illuminate\\Events\\Dispatcher))
#12 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Container/Util.php(41): Illuminate\\Container\\BoundMethod::Illuminate\\Container\\{closure}()
#13 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(93): Illuminate\\Container\\Util::unwrapIfClosure(Object(Closure))
#14 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Container/BoundMethod.php(35): Illuminate\\Container\\BoundMethod::callBoundMethod(Object(Illuminate\\Foundation\\Application), Array, Object(Closure))
#15 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Container/Container.php(662): Illuminate\\Container\\BoundMethod::call(Object(Illuminate\\Foundation\\Application), Array, Array, NULL)
#16 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Console/Command.php(211): Illuminate\\Container\\Container->call(Array)
#17 /home/site/wwwroot/vendor/symfony/console/Command/Command.php(326): Illuminate\\Console\\Command->execute(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#18 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Console/Command.php(180): Symfony\\Component\\Console\\Command\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Illuminate\\Console\\OutputStyle))
#19 /home/site/wwwroot/vendor/symfony/console/Application.php(1081): Illuminate\\Console\\Command->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#20 /home/site/wwwroot/vendor/symfony/console/Application.php(320): Symfony\\Component\\Console\\Application->doRunCommand(Object(Laravel\\Pulse\\Commands\\CheckCommand), Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#21 /home/site/wwwroot/vendor/symfony/console/Application.php(174): Symfony\\Component\\Console\\Application->doRun(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#22 /home/site/wwwroot/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php(201): Symfony\\Component\\Console\\Application->run(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#23 /home/site/wwwroot/artisan(35): Illuminate\\Foundation\\Console\\Kernel->handle(Object(Symfony\\Component\\Console\\Input\\ArgvInput), Object(Symfony\\Component\\Console\\Output\\ConsoleOutput))
#24 {main}
"} 

   RedisException 

  Connection refused

  at vendor/laravel/framework/src/Illuminate/Redis/Connectors/PhpRedisConnector.php:161
    157▕         if (version_compare(phpversion('redis'), '5.3.0', '>=') && ! is_null($context = Arr::get($config, 'context'))) {
    158▕             $parameters[] = $context;
    159▕         }
    160▕ 
  ➜ 161▕         $client->{$persistent ? 'pconnect' : 'connect'}(...$parameters);
    162▕     }
    163▕ 
    164▕     /**
    165▕      * Create a new redis cluster instance.

      +23 vendor frames 

  24  artisan:35
      Illuminate\Foundation\Console\Kernel::handle(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))

```

**Comment by salahhusa9** [comment]
i want to change connection, if i do it with `PULSE_REDIS_CONNECTION` the don't tack it, he use defult redis connection @timacdonald

**Comment by salahhusa9** [comment]
and olso if i change `PULSE_CACHE_DRIVER` he don't work he stile connect to defult

**Comment by salahhusa9** [comment]
(in my project `CACHE_DRIVER` is azure_redis, but pulse he stile use `redis`

**Comment by salahhusa9** [comment]
i solved, problem is in lock:
```php
//cache.php

        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
            'lock_connection' => 'default',
        ],

        'azure_redis' => [
            'driver' => 'redis',
            'connection' => 'azure_cache',
            'lock_connection' => 'default',
        ],

```

solution must be change lock_connection

```php
//cache.php

        'redis' => [
            'driver' => 'redis',
            'connection' => 'cache',
            'lock_connection' => 'default',
        ],

        'azure_redis' => [
            'driver' => 'redis',
            'connection' => 'azure_cache',
            'lock_connection' => 'azure_cache',
        ],

```
