### ISSUE TITLE
RedisClientException on pulse:work (ERR syntax error)

### ISSUE THREAD

**Issue by rikvdlooi** [laravel/pulse#163]
### Pulse Version

v1.0.0-beta5

### Laravel Version

v10.28.0

### PHP Version

8.2.12

### Database Driver & Version

MySQL 8.0.35-0ubuntu0.22.04.1 and Redis 6.0.16

### Description

I'm trying out Laravel Pulse with `PULSE_INGEST_DRIVER=redis`

In the `AppServiceProvider` I've added the following code:

```php
public function boot(): void {
    //

    Pulse::handleExceptionsUsing(function ($e) {
        report($e);
    });
}
```

I'm running

```shell
php artisan pulse:work
```

In the log file I see the following entries

```
[2023-12-06 09:41:23] local.ERROR: ERR syntax error {"userId":14,"exception":"[object] (Laravel\\Pulse\\Support\\RedisClientException(code: 0): ERR syntax error at /my-project/vendor/laravel/pulse/src/Support/RedisAdapter.php:117)
[stacktrace]
#0 /my-project/vendor/laravel/framework/src/Illuminate/Support/helpers.php(307): Laravel\\Pulse\\Support\\RedisAdapter->Laravel\\Pulse\\Support\\{closure}()
#1 /my-project/vendor/laravel/pulse/src/Support/RedisAdapter.php(115): tap()
#2 /my-project/vendor/laravel/pulse/src/Support/RedisAdapter.php(72): Laravel\\Pulse\\Support\\RedisAdapter->handle()
#3 /my-project/vendor/laravel/pulse/src/Ingests/RedisIngest.php(58): Laravel\\Pulse\\Support\\RedisAdapter->xtrim()
#4 /my-project/vendor/laravel/pulse/src/Pulse.php(492): Laravel\\Pulse\\Ingests\\RedisIngest->trim()
#5 /my-project/vendor/laravel/pulse/src/Pulse.php(295): Laravel\\Pulse\\Pulse->rescue()
#6 /my-project/vendor/laravel/framework/src/Illuminate/Support/Lottery.php(141): Laravel\\Pulse\\Pulse->Laravel\\Pulse\\{closure}()
#7 /my-project/vendor/laravel/framework/src/Illuminate/Support/Lottery.php(120): Illuminate\\Support\\Lottery->runCallback()
#8 /my-project/vendor/laravel/pulse/src/Pulse.php(296): Illuminate\\Support\\Lottery->choose()
#9 /my-project/vendor/laravel/pulse/src/PulseServiceProvider.php(134): Laravel\\Pulse\\Pulse->store()
#10 /my-project/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(227): Laravel\\Pulse\\PulseServiceProvider->Laravel\\Pulse\\{closure}()
#11 /my-project/public/index.php(61): Illuminate\\Foundation\\Http\\Kernel->terminate()
#12 {main}
"} 
```

In the dashboard I do not see new data coming in. Running with `PULSE_INGEST_DRIVER=storage` does work.

### Steps To Reproduce

- Use redis as the ingest driver
- Report pulse errors
- Click around in the application to generate data
- Run `php artisan pulse:work
- Check the logs and see the errors

**Comment by rikvdlooi** [comment]
Correction: new data is coming in, and there are no new errors.
Maybe there was something specific that triggered the Redis error.
I've added an extra debug in `RedisAdapter.php` in the `handle` method to log the `$args` if an exception is thrown. I'll update if I find more information.

**Comment by rikvdlooi** [comment]
I've got another error. But I was stopping and starting the work command a lot trying to get more info. So maybe that's relevant.

The contents of `$args`:
```
[2023-12-06 10:27:48] local.INFO: array (
  0 => 'XTRIM',
  1 => 'dev_topical_meetings_database_laravel:pulse:ingest',
  2 => 'MINID',
  3 => '~',
  4 => '1701250068484',
)  
```

**Comment by rikvdlooi** [comment]
When reading through the redis documentation I found that they added the `MINID` trimming strategy to the `XTRIM` command in Redis version 6.2.0.

See: https://redis.io/commands/xtrim/ at the bottom of the page.

So it seems that my redis version (6.0.16) doesn't support this yet.

**Comment by rikvdlooi** [comment]
Thanks for your help and the great package!

**Comment by timacdonald** [comment]
Sorry for the troubles here. I've opened a PR to help with debugging this in the future: https://github.com/laravel/pulse/pull/168
