### ISSUE TITLE
Deprecation notice: number_format(): Passing null to parameter #1 ($num) of type float is deprecated

### ISSUE THREAD

**Issue by dtvmedia** [laravel/pulse#166]
### Pulse Version

1.0.0-beta4

### Laravel Version

10.35.0

### PHP Version

8.2.11

### Livewire Version

3.2.6

### Description

In our application we have enabled the deprecation log and every time we open the Laravel Pulse dashboard this log got spammed with many of the following deprecation notices:

```
ErrorException: number_format(): Passing null to parameter #1 ($num) of type float is deprecated in /home/api/storage/framework/views/79c5c750a6a0e546ca01496280c45462.php:342
Stack trace:
#0 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Support/helpers.php(432): Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#1 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(101): with()
#2 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(70): Illuminate\Foundation\Bootstrap\HandleExceptions->handleDeprecationError()
#3 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(254): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError()
#4 [internal function]: Illuminate\Foundation\Bootstrap\HandleExceptions->Illuminate\Foundation\Bootstrap\{closure}()
#5 /home/api/storage/framework/views/79c5c750a6a0e546ca01496280c45462.php(342): number_format()
#6 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(37): include('...')
#7 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(38): Laravel\Pulse\Livewire\Cache->Livewire\Mechanisms\ExtendBlade\{closure}()
#8 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/View/Engines/CompilerEngine.php(72): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->evaluatePath()
#9 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/ExtendBlade/ExtendedCompilerEngine.php(16): Illuminate\View\Engines\CompilerEngine->get()
#10 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/View/View.php(207): Livewire\Mechanisms\ExtendBlade\ExtendedCompilerEngine->get()
#11 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/View/View.php(190): Illuminate\View\View->getContents()
#12 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/View/View.php(159): Illuminate\View\View->renderContents()
#13 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(245): Illuminate\View\View->render()
#14 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(289): Livewire\Mechanisms\HandleComponents\HandleComponents->Livewire\Mechanisms\HandleComponents\{closure}()
#15 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(235): Livewire\Mechanisms\HandleComponents\HandleComponents->trackInRenderStack()
#16 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/HandleComponents/HandleComponents.php(111): Livewire\Mechanisms\HandleComponents\HandleComponents->render()
#17 /home/api/builds/814/vendor/livewire/livewire/src/LivewireManager.php(96): Livewire\Mechanisms\HandleComponents\HandleComponents->update()
#18 /home/api/builds/814/vendor/livewire/livewire/src/Mechanisms/HandleRequests/HandleRequests.php(90): Livewire\LivewireManager->update()
#19 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/ControllerDispatcher.php(46): Livewire\Mechanisms\HandleRequests\HandleRequests->handleUpdate()
#20 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Route.php(259): Illuminate\Routing\ControllerDispatcher->dispatch()
#21 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Route.php(205): Illuminate\Routing\Route->runController()
#22 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Router.php(806): Illuminate\Routing\Route->run()
#23 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Routing\Router->Illuminate\Routing\{closure}()
#24 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Middleware/SubstituteBindings.php(50): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#25 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Routing\Middleware\SubstituteBindings->handle()
#26 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/VerifyCsrfToken.php(78): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#27 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\VerifyCsrfToken->handle()
#28 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/View/Middleware/ShareErrorsFromSession.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#29 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\View\Middleware\ShareErrorsFromSession->handle()
#30 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(121): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#31 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\Session\Middleware\StartSession->handleStatefulRequest()
#32 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Session\Middleware\StartSession->handle()
#33 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#34 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\AddQueuedCookiesToResponse->handle()
#35 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#36 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Cookie\Middleware\EncryptCookies->handle()
#37 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#38 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Router.php(805): Illuminate\Pipeline\Pipeline->then()
#39 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Router.php(784): Illuminate\Routing\Router->runRouteWithinStack()
#40 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Router.php(748): Illuminate\Routing\Router->runRoute()
#41 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Routing/Router.php(737): Illuminate\Routing\Router->dispatchToRoute()
#42 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(200): Illuminate\Routing\Router->dispatch()
#43 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\Foundation\Http\Kernel->Illuminate\Foundation\Http\{closure}()
#44 /home/api/builds/814/vendor/livewire/livewire/src/Features/SupportDisablingBackButtonCache/DisableBackButtonCacheMiddleware.php(19): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#45 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Livewire\Features\SupportDisablingBackButtonCache\DisableBackButtonCacheMiddleware->handle()
#46 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#47 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ConvertEmptyStringsToNull->handle()
#48 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(36): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#49 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\TrimStrings->handle()
#50 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#51 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\ValidatePostSize->handle()
#52 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(99): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#53 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Foundation\Http\Middleware\PreventRequestsDuringMaintenance->handle()
#54 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Http/Middleware/HandleCors.php(49): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#55 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\HandleCors->handle()
#56 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#57 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\Http\Middleware\TrustProxies->handle()
#58 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}()
#59 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(175): Illuminate\Pipeline\Pipeline->then()
#60 /home/api/builds/814/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(144): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter()
#61 /home/api/builds/814/public/index.php(51): Illuminate\Foundation\Http\Kernel->handle()
#62 {main}
```

### Steps To Reproduce

Just open the Laravel Pulse dashboard with enabled deprecation logs.

**Comment by timacdonald** [comment]
Thanks for reporting this. I'm unable to replicate this locally.

Could you please take a look in the file `storage/framework/views/79c5c750a6a0e546ca01496280c45462.php` and share the content found on line `342`.

That might give us a hint as to which component this is happening on. Thanks.

**Comment by timacdonald** [comment]
Perfect. Working on a fix now.
